version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 99
    schedule:
      interval: daily
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
