change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

categories:
  - title: Breaking changes
    label: breaking
  - title: Features
    label: feature
  - title: Enhancements
    labels:
      - enhancement
      - performance
  - title: Bug Fixes
    label: fix
  - title: Documentation changes
    label: documentation
  - title: Dependency updates
    label: dependencies
  - title: Maintenance
    labels:
      - refactor
      - chore
  - title: Tests
    label: test

exclude-labels:
  - benchmark
  - ci
  - version

template: |
  $CHANGES
