$schema: "https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json"

heading-style:
  style: atx
ul-style:
  style: dash
no-trailing-spaces:
  br_spaces: 0
no-hard-tabs:
  spaces_per_tab: 2
line-length: false
no-duplicate-heading:
  siblings_only: true
no-trailing-punctuation:
  punctuation: .,;:!?。，；：！？、
no-blanks-blockquote: false
ol-prefix:
  style: one
no-inline-html:
  allowed_elements:
    - details
    - summary
hr-style:
  style: ---
no-emphasis-as-heading: false
fenced-code-language:
  allowed_languages:
    - text
    - csharp
    - razor
    - typescript
    - javascript
    - python
    - html
    - css
    - markdown
    - xml
    - json
    - yaml
    - shell
    - powershell
    - batch
    - bash
    - editorconfig
    - dockerfile
  language_only: true
required-headings: false
code-block-style:
  style: fenced
emphasis-style:
  style: asterisk
strong-style:
  style: asterisk
link-image-style:
  collapsed: false
  full: false
  shortcut: false
  url_inline: false
table-pipe-style:
  style: leading_and_trailing
