default: true
heading-increment: true
first-heading-h1: false
heading-style:
  style: atx
ul-style:
  style: dash
list-indent: true
ul-start-left: true
ul-indent:
  indent: 2
no-trailing-spaces:
  br_spaces: 2
  list_item_empty_lines: false
no-hard-tabs: true
no-reversed-links: true
no-multiple-blanks:
  maximum: 1
line-length: false
commands-show-output: true
no-missing-space-atx: true
no-multiple-space-atx: true
blanks-around-headings:
  lines_above: 1
  lines_below: 1
heading-start-left: true
no-duplicate-heading: false
single-title: true
no-trailing-punctuation:
  punctuation: .,;:!?。，；：！？、
no-multiple-space-blockquote: true
no-blank-blockquote: true
ol-prefix:
  style: one
list-marker-space:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1
blanks-around-fences: true
blanks-around-lists: true
no-inline-html: true
no-bare-urls: true
hr-style:
  style: ---
no-emphasis-as-heading: false
no-space-in-emphasis: true
no-space-in-code: true
no-space-in-links: true
fenced-code-language: true
first-line-heading:
  level: 1
no-empty-links: true
required-headings: false
proper-names: true
no-alt-text: true
code-block-style:
  style: fenced
single-trailing-newline: true
