name: Build(.NET)

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.tt'
      - '**/*.xaml'
      - '**/*.razor'
      - '**/*.cshtml'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.props'
      - '**/*.targets'
      - '**/.editorconfig'
      - '**/.globalconfig'

permissions: {}

jobs:
  main:
    name: Main
    uses: finphie/Actions/.github/workflows/build-dotnet.yml@main
