name: Build(Markdown)

on:
  pull_request:
    paths:
      - '**/*.md'
      - .markdownlint.yml

permissions: {}

jobs:
  main:
    name: Main
    uses: finphie/Actions/.github/workflows/build-markdown.yml@main
