name: Normalize line endings

on:
  pull_request:

permissions:
  contents: write

jobs:
  main:
    name: Main
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    uses: finphie/Actions/.github/workflows/normalize.yml@main
