name: PR

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: TimonVS/pr-labeler-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
